### ISSUE TITLE
Doesn't work with Factions 2.8.16

### ISSUE THREAD

**Issue by AgentCortez** [MarkehMe/FactionsWarps#11]
Doesn't work with Factions 2.8.16.

Guess it doesn't have latest update?

**Comment by markhughes** [comment]
I haven't tested it yet, can you pass on the error logs? 

This would be an issue with FactionsFramework, not FactionsWarps.

**Comment by AgentCortez** [comment]
`[22:14:08] [Server thread/INFO]: [Factions] Enabling Factions v2.8.16
[22:14:08] [Server thread/INFO]: [Factions 2.8.16] === ENABLE START ===
[22:14:09] [Server thread/INFO]: [Factions 2.8.16] Integration Activated IntegrationWorldGuard
[22:14:09] [Server thread/INFO]: [Factions 2.8.16] Integration Activated IntegrationSpigot
[22:14:09] [Server thread/INFO]: [Factions 2.8.16] === ENABLE COMPLETE (Took 798ms) ===`

`[22:14:11] [Server thread/INFO]: [FactionsFramework] Enabling FactionsFramework v1.1.1
[22:14:11] [Server thread/INFO]: [FactionsFramework] Factions version is: Factions_2_8_8`
Version is incorrect, its 2.8.16.

`[22:14:13] [Server thread/INFO]: [FactionsWarps] Enabling FactionsWarps v1.1.1
[22:14:13] [Server thread/ERROR]: Error occurred while enabling FactionsWarps v1.1.1 (Is it up to date?)
java.lang.NoSuchMethodError: com.massivecraft.factions.cmd.CmdFactions.addChild(Lcom/massivecraft/massivecore/command/MassiveCommand;)V
    at me.markeh.factionsframework.layer.layer_2_8_8.CommandManager_2_8_8.add(CommandManager_2_8_8.java:33) ~[?:?]
    at me.markeh.factionswarps.FactionsWarps.onEnable(FactionsWarps.java:59) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]`

**Comment by AgentCortez** [comment]
Has this been fixed ?

**Comment by markhughes** [comment]
Haven't created a fix for it yet. Still can't work out what is causing the issues 😞

**Comment by AgentCortez** [comment]
Thanks for the update :+1:

**Comment by markhughes** [comment]
Fixed. Update FactionsFramework. 👍  😁
